### ISSUE TITLE
Please remove Bulma dependency

### ISSUE THREAD

**Issue by focussing** [14nrv/vue-form-json#20]
Bulma has bad IE11 support, so that would make this beautiful module useless for a lot of applications.

**Comment by 14nrv** [comment]
Hi,

Bulma is not required & not imported by default.
You can can overwrite some class : on .field & real field (input...), ex:

`const formFields = [{
  label: 'the label',
  attr: { class: 'classOnInput' },
  field: { attr: { class: 'classOnFieldClassName' } }
}]`

**Comment by focussing** [comment]
Hi!

Beautiful....
Thank you for your fast response.
Just setting up a new project :)

**Comment by focussing** [comment]
If only Bulma would be supporting IE11 (almost all schools in NL still use IE11).
Bulma is so great...
