### ISSUE TITLE
Add support `ref` attribute

### ISSUE THREAD

**Issue by djmonta** [14nrv/vue-form-json#22]
I've been working around the registration form using the codes and [baianat/vee-validate](https://github.com/baianat/vee-validate).
I found some [Validation Rules \(VeeValidate doc\)](https://baianat.github.io/vee-validate/guide/rules.html#after) which the field must have `ref` attribute and value set.

I tried using below json generate the form, but not reflected to the DOM correctly which means the field value couldn't validate.
```
{
  "label": "Label",
  "type": "text",
  "attr" : {
    "ref" : "label"
  }
}
```

**Comment by 14nrv** [comment]
Hi,

it s already in [the roadmap](https://github.com/14nrv/vue-form-json/projects/1#card-17460250) :)

**Comment by igorgoncalves** [comment]
Any news about this issue? Can you help?

**Comment by 14nrv** [comment]
No news for now.

IMO, to add this new feature, this will need perhaps a huge refacto, but BTW perhaps you can simply change a bit the UX of ur form :)

**Comment by 14nrv** [comment]
this refacto has just been done with the new v.3 and should help to do a [Cross Field Validation](https://logaretm.github.io/vee-validate/advanced/cross-field-validation.html#targeting-other-fields)

Note that [`name` is directly bind & `vid` is allowed in the json](https://github.com/14nrv/vue-form-json/blob/39beab792da168e0e483d398f53e75d1a8a374a5/src/components/Fields/Control.vue#L4) for the ValidationProvider, I ll try do add an example soon

**Comment by 14nrv** [comment]
@djmonta  @igorgoncalves 

Here it s a working example with for Cross Field Validation with the v3.0.1 (I ll update the CodeSandBox with this example soon)
```js
// main.js

// ...
Object.keys(rules).forEach(rule => {
  extend(rule, {
    ...rules[rule],
    message: messages[rule]
  })
})

extend('password', {
  params: ['target'],
  validate: (value, { target }) => value === target,
  message: 'Password confirmation does not match'
})
// ...
```

```
// fields.json

[
  [
    {
      "label": "PasswordLabel",
      "type": "password",
      "pattern": ".[0-9]{4,}$",
      "help": "(>=5 digits)"
    },
    {
      "label": "Confirmation",
      "type": "password",
      "rules": {
        "password": "@PasswordLabel"
      }
    }
  ]
]
```
