### ISSUE TITLE
Support specifying name or id for field

### ISSUE THREAD

**Issue by djmonta** [14nrv/vue-form-json#23]
Support specifying `name` or `id` in ascii characters in the field definition would be nice.  

Because I am using Japanese in label, using slugify the label string for name and id causes JS errors / warnings.

**Comment by 14nrv** [comment]
Can u make a [Codesandbox](https://codesandbox.io/s/mxow346yj?autoresize=1&hidenavigation=1&module=%2Fsrc%2FApp.vue&view=preview) where we can see the error pls?
(I have no errors on load, when I try with [ur json](https://raw.githubusercontent.com/djmonta/vue-form-json/dev/src/components/Form/fields-charge.json))

**Comment by djmonta** [comment]
Hi,

I've made an [example](https://codesandbox.io/embed/vue-form-json-demo-88ljj).
Noticed no errors or warnings, it's my mis-understanding.  
Though, while inspecting DOM elements, some inputs without any ascii characters in label have no name and id attributes.

**Comment by 14nrv** [comment]
Hi,
If the string is returned by default it should fix ur problem, what do you think @djmonta ?

`export const slug = str => slugify(str.toLowerCase()) || str`

Result
```
<div class="field">
  <label data-v-412ceda4="" for="本社名 または 屋号" class="label">
    <p data-v-412ceda4="">本社名 または 屋号<span data-v-412ceda4=""><sup data-v-412ceda4="" class="has-text-grey-light is-size-7"> *</sup></span></p>
  </label>
  <div class="control">
    <input id="本社名 または 屋号" name="本社名 または 屋号" required="required" minlength="4" maxlength="50" type="text" class="input" data-vv-name="本社名 または 屋号" aria-required="true" aria-invalid="false">
  </div>
</div>
```

**Comment by djmonta** [comment]
Hello,

I think that is one solution for fixing problem, but not sure it is allowed to use non-ascii characters `for` and `id` attributes in general HTML.

If I could specify `name` or `alternative_label` (explicits only ascii characters) in json, then use this to the `for` / `id` / `name` would be nicer.

For example: in json
```json
{
  "label" : "本社名 または 屋号",
  "name" : "Company Name",
}
```
render to: 
```html
<div class="field">
  <label data-v-412ceda4="" for="company_name" class="label">
    <p data-v-412ceda4="">本社名 または 屋号<span data-v-412ceda4=""><sup data-v-412ceda4="" class="has-text-grey-light is-size-7"> *</sup></span></p>
  </label>
  <div class="control">
    <input id="comapny_name" name="company_name" required="required" minlength="4" maxlength="50" type="text" class="input" data-vv-name="本社名 または 屋号" aria-required="true" aria-invalid="false">
  </div>
</div>
```
