### ISSUE TITLE
Button class 

### ISSUE THREAD

**Issue by minasvisual** [14nrv/vue-form-json#26]
Hety man, nice job with this plugin.

I use bootstrap template and customize fields easily, but buttons have no option to change class.
````
 btnSubmitText: {
    type: String,
    default: 'Submit',
   -----------------------
   className: "btn btn-success"
   -------------------
 },
````
i suppose, this new line solve the issue.

**Comment by 14nrv** [comment]
Hi @minasvisual,

Thanks for your feedback & for using this project, I ll take a look to this issue asap
ps: this props `btnSubmitText` is just for the text of the button
