### ISSUE TITLE
Form values are empty after getting 'cannot set property of undefined error'

### ISSUE THREAD

**Issue by oeway** [14nrv/vue-form-json#45]
Hi thanks for your nice work on the library.
I am having some trouble in using it whin my app, specifically, I am using the same code as you provide in the example, the form shows on the interface, but when clicking submit, the values returned is empty (`{}`).

This is the preview page of the app: https://deploy-preview-48--kaibu.netlify.app/#/app which you can fill in the form and click submit to see the empty values.  Here is the source code: https://github.com/imjoy-team/kaibu/pull/48/files

In the console, I can see the following warning and errors:
```
vue.runtime.esm.js?0bb2:619 [Vue warn]: $attrs is readonly.

found in

---> <ValidationObserver>
       <Form>
         <FormWidget> at src/components/widgets/FormWidget.vue
           <BTabItem>
             <BTabs>
               <BSidebar>
                 <ImageViewer> at src/components/ImageViewer.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?0bb2:619
...
vue.runtime.esm.js?0bb2:619 [Vue warn]: $listeners is readonly.

found in

---> <ValidationObserver>
       <Form>
         <FormWidget> at src/components/widgets/FormWidget.vue
           <BTabItem>
             <BTabs>
               <BSidebar>
                 <ImageViewer> at src/components/ImageViewer.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?0bb2:619
...
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "value": "TypeError: Cannot set property 'First Name' of undefined"

found in

---> <Control>
       <Form>
         <FormWidget> at src/components/widgets/FormWidget.vue
           <BTabItem>
             <BTabs>
               <BSidebar>
                 <ImageViewer> at src/components/ImageViewer.vue
                   <App> at src/App.vue
                     <Root>
warn @ vue.runtime.esm.js?2b0e:619
...
vue.runtime.esm.js?2b0e:1888 TypeError: Cannot set property 'First Name' of undefined
    at VueComponent.value (vue-form-json.common.js?0df0:9967)
    at Watcher.run (vue.runtime.esm.js?2b0e:4568)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4310)
    at Array.eval (vue.runtime.esm.js?2b0e:1980)
    at flushCallbacks (vue.runtime.esm.js?2b0e:1906)
```

**Comment by 14nrv** [comment]
Hi, thanks for your interest in this project

Can you reproduce this bug on a CodeSandbox with just the form?

**Comment by oeway** [comment]
Hi, I figured out a fix, I just need to remove my package-lock.json and install it again. I don't know exactly why, but I think it was because some outdated dependency that cause the issue. I was trying to reproducing the issue on CodeSandbox, and I couldn't until I use the same package-lock.json file.

Let's close this issue, thanks you for your prompt anwser.
