### ISSUE TITLE
Support tags

### ISSUE THREAD

**Issue by oeway** [14nrv/vue-form-json#46]
It would be nice to support editing an array of tags by using:  https://bulma.io/documentation/elements/tag/

**Comment by 14nrv** [comment]
Do you have a final screenshot/example of your need?

**Comment by oeway** [comment]
Hi, there are two cases which will be super useful for me:
1. a input box allows users to create/remove new tags like this, and in this case, user can type free text for the tags:
<img width="394" alt="Screenshot 2021-01-29 at 12 35 53" src="https://user-images.githubusercontent.com/478667/106270624-90114280-622e-11eb-8700-e685d8c9c9a4.png">
2. similarly to 1 but only allowed to select preconfigured labels from a dropdown menu

In both cases, user can click the cross sign to remove selected labels.

For my project, I will use it to annotate images, but I think it will be generally useful for many applications.

**Comment by 14nrv** [comment]
1. you could already do something like this ("not in the ideal way") with vue-form-json but without the tag rendering, in fact: you could create a form with just an input text to create a tag, and an other form with input checkbox selected by default
2. you would need a form with a [select multiple](https://github.com/14nrv/vue-form-json/projects/1#card-23418007)

**Comment by oeway** [comment]
Thank you for your quick response, when you say "a form" do you mean I can combine multiple form together? That will be less ideal as you can imagine, the point for me to use vue-form-json is the simplicity. 

Yes, that's exactly what I wanted, we can cover both case 1 and 2 by adding options for autocomplete. If we enable open on focus, then it allows us select from a list. See here https://buefy.org/documentation/taginput/#autocomplete

Could you please add a field for this? This would be awesome!

**Comment by 14nrv** [comment]
vue-form-json allow named slot, and I am wondering if this could help you with your case.
Perhaps you could try to add a taginput component from buefy in a slot and see what's happens.

PS: there is also [buefy-form-generator](https://github.com/bitkris-dev/buefy-form-generator)

**Comment by oeway** [comment]
I see, for named slots, do you have an example on how I can pass the properties of the field to the slot?

I guess another disadvantage is that the api will be less ideal for the user if we end up using the slots.

**Comment by 14nrv** [comment]
> do you have an example on how I can pass the properties of the field to the slot?
just like the [buefy example](https://buefy.org/documentation/taginput/#templated-autocomplete) that u could put in a separate component and add it inside the slot

**Comment by oeway** [comment]
Hi @14nrv My question is how I can pass custom fields into the slot. For example, I have a field definition like this: 
```js
const formFields = [
    { slot: 'tagInput', attr: { label: "book tags", options: ["drama", "sci-fi"]}}
]
```

I am not sure how I can pass my `attr` into the component, we will have something like the following?
```html
 <form-json ...>
  <template slot="tagInput" >
          <b-taginput
                v-model="tags"
                :data="options"
                autocomplete
                icon="label"
                placeholder="Add a tag">
                <template #empty>
                    There are no items
                </template>
            </b-taginput>
  </template>
</form-json>
```

When the user click Submit, how I can retrieve the selected tags?  How do we apply validation rules? 

Would be great if you can give a more detailed example, thanks a lot in advance!

**Comment by oeway** [comment]
I sent a PR for supporting this : https://github.com/14nrv/vue-form-json/pull/47
Please let me know what you think.

BTW, I am thinking that we can potentially use slot to support custom field types, similar to slots but using same api as standard field types such as input and radio. What do you think?

**Comment by 14nrv** [comment]
@oeway here is a [codeSandbox example](https://codesandbox.io/s/vue-form-json-taginput-demo-zqop0?file=/src/components/InputTag.vue), done without any change on vue-form-json. In this example, the validation is working.
If it's ok for you, can u close this issue & your PR?

<img width="484" alt="Capture d’écran 2021-02-20 à 18 45 44" src="https://user-images.githubusercontent.com/34603467/108604396-fb71ae80-73ad-11eb-9508-b82ad64a5ee8.png">

**Comment by oeway** [comment]
Hi, thanks for looking into this! I had a look at your implementation, and I found you simply hard coded the tag input field which is not be possible for my case. And the point of using vue-json-form for me is to do dynamic UI rendering with json data from the user. In this case, all the tag input properties should be contained in the json object.

**Comment by 14nrv** [comment]
Hi, I just fixed the Travis issue.
I think I ll make a PR for the slot props soon, I just have to make unit test before & update the README.
For the second part, I am wondering if exposing the control component with a slot inside & also the mixin could help, WDYT?

**Comment by oeway** [comment]
Great! I will close my PR then.
> For the second part, I am wondering if exposing the control component with a slot inside & also the mixin could help, WDYT?

Sounds like a good idea! Looking forward to seeing your implementation.

**Comment by 14nrv** [comment]
Finally, I used the scoped slot, I ll push it soon. I added to the props: a `updateFormValues` function and a `isFormReseted` boolean that u will have to watch

**Comment by oeway** [comment]
That's great! Thank you!


Is there a chance to improve the api for extending the field types using custom scoped slots? I.e. in the fields definition the user can specify a custom type just like the existing ones (instead of a slot)?

**Comment by 14nrv** [comment]
Good idea, I ll have a look at it later, BTW a PR is always welcome :)

**Comment by 14nrv** [comment]
Hi @oeway,

Here you can find an [almost done example](https://codesandbox.io/s/vue-form-json-demo-dgk2n) with custom fields. There is just one TODO inside for the InputFile `deleteDropFile` function (the submit button is still active after removing an uploaded file).

**Comment by oeway** [comment]
> Hi @oeway,
> 
> Here you can find an [almost done example](https://codesandbox.io/s/vue-form-json-demo-dgk2n) with custom fields. There is just one TODO inside for the InputFile `deleteDropFile` function (the submit button is still active after removing an uploaded file).

Just tried it and it's awesome! Thanks for the great work.


I was thinking whether we can also support this type of json field interface.

Meaning allowing this:
```json
 {
    "type": "tags",
    "options": ["drama", "sci-fi"],
    "label": "Tag(s)",
    "placeholder": "Add a tag"
  },
```

Instead of this:
```json
 {
    "slot": "tags",
    "props": {
      "options": ["drama", "sci-fi"],
      "label": "Tag(s)",
      "placeholder": "Add a tag"
    }
  },
```

A very add-hoc approach is to simply check if the field type is supported internally, if not, we convert it into a slot. But you may have a better method and potentially supported directly.

**Comment by 14nrv** [comment]
Could you please create a new issue with this?
