### ISSUE TITLE
Get file objects in form values

### ISSUE THREAD

**Issue by oeway** [14nrv/vue-form-json#50]
Hi, I am using the slot to extend field types to a drop zone to get files, however, it doesn't pass through eventually due the the JSON serialisation step:
https://github.com/14nrv/vue-form-json/blob/8d94a5aba911c0d167be3065305f35f5d642fc85/src/components/Form/Form.vue#L131

Would be great if we can implement it in a different way so we can let the files and other non-json serialisable object to go through.

UPDATE: just tested by removing the json seriallization part, and I noticed that `humps` will still destroy the file object during `camelizeKeys`, we need to also fix that.

**Comment by 14nrv** [comment]
Hi, thanks for reporting this.

Could you please provide a simple CodeSandbox showing this issue?

**Comment by oeway** [comment]
I am current using a forked version. However, I saw you have merged https://github.com/14nrv/vue-form-json/pull/48 , and how can one update the field value of a scoped slot field?

**Comment by 14nrv** [comment]
I got a fix for the file object, I ll push it soon
