### ISSUE TITLE
Tooltip for each field

### ISSUE THREAD

**Issue by oeway** [14nrv/vue-form-json#57]
Hi, I am wondering is there a way to add more detailed description about each field? Maybe something like a tooltip?

**Comment by 14nrv** [comment]
Hi, for now, there is a [`help` attribute](https://github.com/14nrv/vue-form-json/blob/b8a52fe08ed01f45c8677a03decce147e7b8511c/src/components/Fields/Label.vue#L4)

const formFields = [ [{ label: 'label one', help: 'help text content' }] ]

**Comment by oeway** [comment]
Nice, that helps, thanks! Maybe just document it then?

**Comment by oeway** [comment]
@14nrv I have been using the help text and it works well, however I noticed that it cannot display links. It's rather common to have a link in the help text to provide user extra details. Could you please make the links in the help text clickable?

**Comment by 14nrv** [comment]
@oeway u can already do it I think with a `html` attribute, there is an example of this attribute in the codeSandbox link ("Custom attr & validation")

**Comment by oeway** [comment]
@14nrv Thank you! Yes, indeed the `html` field does the trick.
