### ISSUE TITLE
Compatibility with json schema

### ISSUE THREAD

**Issue by aantn** [14nrv/vue-form-json#58]
Hi,
Thank you for releasing vue-form-json. It looks really cool and I was considering rolling something like this myself so you've saved me a lot of time.

For my use case, I have input data in json-schema format. It's similar enough that I can probably just make it work, but I think improved compatibility with json schema would be very cool. One area that currently isn't compatible is the rules validation.

I might do some work on compatibility and first wanted to ask if you have any thoughts on this. Would you be open to accepting changes back into the project? Are there any pitfalls I should be aware of?

**Comment by 14nrv** [comment]
Hey,

Thanks for your interest in this project.

Json-schema is already something that I have in mind as you can see [here](https://github.com/14nrv/vue-form-json/projects/1#card-47296239). But, I would prefer, if possible, to have only one schema in the end, and not one for the form and another one for the UI. For the rules validation, this project uses [vee-validate](https://logaretm.github.io/vee-validate/guide/rules.html#rules).

Supporting also json-schema could be perhaps a good first step if there are no breaking changes and depending also of the size of the "mapping".

ps: you could be interested in a project like [vue-form-json-schema](https://github.com/jarvelov/vue-form-json-schema)

**Comment by 14nrv** [comment]
closed due to no answer, feel free to open a new issue if u want
